name: ShowCommitIDs

on:
  pull_request:
    branches: [master, main]
    types: [opened, edited, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:

  show-commit-ids:

    if: github.event.issue.pull_request || (github.event_name == 'pull_request')

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Fetch latest changes
      run: git fetch origin main:main
      
    - name: Get commit ids
      id: commit_id
      run: |
        FULL_COMMIT_ID="${{ github.event.pull_request.head.sha }}"
        SHORT_COMMIT_ID="${FULL_COMMIT_ID::7}"
        echo "CUR_COMMIT_ID=${SHORT_COMMIT_ID}" >> $GITHUB_OUTPUT
        echo "MAIN_COMMIT_ID=$(git rev-parse --short main)" >> $GITHUB_OUTPUT
        echo "HEAD_COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
    - name: Show commit ids
      run: |
        echo "CUR: ${{ steps.commit_id.outputs.CUR_COMMIT_ID }}"
        echo "MAIN: ${{ steps.commit_id.outputs.MAIN_COMMIT_ID }}"
        echo "HEAD: ${{ steps.commit_id.outputs.HEAD_COMMIT_ID }}"
    
  
