name: Test Args

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run python
        run: python test_args.py --a 'A' \
                                 --b 'B' \
                                 --c 'C'
                                 
